import test from 'node:test';
import assert from 'node:assert/strict';
import {createDeck,COLORS} from '../public/cards.mjs';
import {newGame,act,view,sets,full,botMove,rent} from '../server/engine.mjs';
import {createRoom,command,snapshot,join} from '../server/rooms.mjs';
const rng=()=>.37;
function fixture(n=2){const g=newGame(Array.from({length:n},(_,i)=>({name:'Player '+i})),rng);g.deck=createDeck();for(const p of g.players){p.hand=[];p.bank=[];p.groups=[]}g.discard=[];return g}
function take(g,pred){const index=g.deck.findIndex(pred);assert.ok(index>=0);return g.deck.splice(index,1)[0]}
function card(g,id,pred){const c=take(g,pred);g.players[id].hand.push(c);return c.id}
function gr(g,id,color,n=1){const cards=[];for(let i=0;i<n;i++)cards.push(take(g,c=>c.kind==='property'&&!c.wild&&c.colors[0]===color));const group={id:'g'+(++g.groupSeq),color,cards,buildings:[]};g.players[id].groups.push(group);return group}
test('106 unique playable cards with correct category counts',()=>{const d=createDeck();assert.equal(d.length,106);assert.equal(new Set(d.map(c=>c.id)).size,106);assert.equal(d.filter(c=>c.kind==='property').length,39);assert.equal(d.filter(c=>c.kind==='money').length,20);assert.equal(d.filter(c=>c.action==='rent').length,13);assert.equal(d.filter(c=>c.action==='pass').length,10)});
test('five starting cards, first player draws two; private snapshots hide other hands and deck',()=>{const g=newGame([{name:'A'},{name:'B'}],rng),v=view(g,0);assert.equal(v.players[0].hand.length,7);assert.equal(v.players[1].handCount,5);assert.equal(v.players[1].hand,undefined);assert.equal(v.deck,undefined);assert.equal(v.drawCount,94)});
test('three play limit and start of empty hand draws five',()=>{const g=fixture();for(let i=0;i<4;i++){const id=card(g,0,c=>c.kind==='money');if(i<3)act(g,0,{type:'play',card:id,mode:'bank'});else assert.throws(()=>act(g,0,{type:'play',card:id,mode:'bank'}),/three/)}act(g,0,{type:'end'},rng);assert.equal(g.players[1].hand.length,5);assert.equal(g.turn,1)});
test('end-of-turn discards go below draw pile and block other actions',()=>{const g=fixture();for(let i=0;i<9;i++)card(g,0,c=>c.kind==='money');act(g,0,{type:'end'});assert.equal(g.phase,'discard');const first=g.players[0].hand[0].id;act(g,0,{type:'discard',card:first});assert.equal(g.deck[0].id,first);act(g,0,{type:'discard',card:g.players[0].hand[0].id});assert.equal(g.turn,1);assert.equal(g.players[0].hand.length,7)});
test('payment uses chosen assets, no change, and banked actions stay banked',()=>{const g=fixture(),debt=card(g,0,c=>c.action==='debt'),cash=take(g,c=>c.kind==='money'&&c.value===10);g.players[1].bank.push(cash);act(g,0,{type:'play',card:debt,target:1});act(g,1,{type:'accept'});assert.throws(()=>act(g,1,{type:'pay',cards:[]}),/enough/);act(g,1,{type:'pay',cards:[cash.id]});assert.equal(g.players[0].bank[0].value,10);assert.equal(g.pending,null);assert.equal(g.players[1].bank.length,0)});
test('partial payment requires everything of value, never hand or rainbow wild',()=>{const g=fixture(),debt=card(g,0,c=>c.action==='debt');gr(g,1,'brown');const rainbow=take(g,c=>c.wild&&c.value===0);g.players[1].groups[0].cards.push(rainbow);card(g,1,c=>c.kind==='money'&&c.value===10);act(g,0,{type:'play',card:debt,target:1});act(g,1,{type:'accept'});assert.throws(()=>act(g,1,{type:'pay',cards:[rainbow.id]}));act(g,1,{type:'pay',cards:[g.players[1].groups[0].cards[0].id]});assert.equal(g.players[1].hand.length,1);assert.equal(g.players[1].groups[0].cards[0].id,rainbow.id)});
test('Just Say No chains restore or cancel the targeted action',()=>{const g=fixture();const debt=card(g,0,c=>c.action==='debt'),no1=card(g,1,c=>c.action==='no'),no2=card(g,0,c=>c.action==='no'),cash=take(g,c=>c.kind==='money'&&c.value===5);g.players[1].bank.push(cash);act(g,0,{type:'play',card:debt,target:1});act(g,1,{type:'no',card:no1});assert.equal(g.pending.responder,0);assert.equal(g.pending.blocked,true);act(g,0,{type:'no',card:no2});assert.equal(g.pending.responder,1);act(g,1,{type:'accept'});act(g,1,{type:'pay',cards:[cash.id]});assert.equal(g.players[0].bank.length,1);assert.equal(g.plays,1)});
test('one player blocking birthday does not cancel debts for other opponents',()=>{const g=fixture(3),birthday=card(g,0,c=>c.action==='birthday'),no=card(g,1,c=>c.action==='no');act(g,0,{type:'play',card:birthday});act(g,1,{type:'no',card:no});act(g,0,{type:'accept'});assert.equal(g.pending.target,2);act(g,2,{type:'accept'});assert.equal(g.pending,null)});
test('Sly Deal cannot steal a complete-set property; Deal Breaker takes buildings too',()=>{const g=fixture(),group=gr(g,1,'brown',2),sly=card(g,0,c=>c.action==='sly');assert.throws(()=>act(g,0,{type:'play',card:sly,target:1,property:group.cards[0].id}),/complete/);const building=take(g,c=>c.action==='house');group.buildings.push(building);const breaker=card(g,0,c=>c.action==='breaker');act(g,0,{type:'play',card:breaker,target:1,group:group.id});act(g,1,{type:'accept'});assert.equal(g.players[0].groups[0].buildings[0].id,building.id);assert.equal(g.players[1].groups.length,0)});
test('Forced Deal transfers both selected properties',()=>{const g=fixture(),mine=gr(g,0,'red'),theirs=gr(g,1,'green'),offer=mine.cards[0].id,want=theirs.cards[0].id,c=card(g,0,x=>x.action==='forced');act(g,0,{type:'play',card:c,target:1,property:want,offer});act(g,1,{type:'accept'});assert.equal(g.players[0].groups[0].cards[0].id,want);assert.equal(g.players[1].groups[0].cards[0].id,offer)});
test('coloured rent targets everyone, any rent targets one; doubles count towards three plays',()=>{const g=fixture(3),group=gr(g,0,'blue',2),r=card(g,0,c=>c.action==='rent'&&!c.single&&c.colors.includes('blue')),d1=card(g,0,c=>c.action==='double'),d2=card(g,0,c=>c.action==='double');act(g,0,{type:'play',card:r,group:group.id,doubles:[d1,d2]});assert.equal(g.pending.amount,32);assert.deepEqual(g.pending.queue,[1,2]);assert.equal(g.plays,3)});
test('hotel needs a house; rent includes both building increments',()=>{const g=fixture(),group=gr(g,0,'brown',2),house=card(g,0,c=>c.action==='house'),hotel=card(g,0,c=>c.action==='hotel');assert.throws(()=>act(g,0,{type:'play',card:hotel,group:group.id}),/house first/);act(g,0,{type:'play',card:house,group:group.id});act(g,0,{type:'play',card:hotel,group:group.id});assert.equal(rent(group),9)});
test('paying away a house moves its unattached hotel to the payer bank',()=>{const g=fixture(),group=gr(g,1,'brown',2),house=take(g,c=>c.action==='house'),hotel=take(g,c=>c.action==='hotel');group.buildings.push(house,hotel);const birthday=card(g,0,c=>c.action==='birthday');act(g,0,{type:'play',card:birthday});act(g,1,{type:'accept'});act(g,1,{type:'pay',cards:[house.id]});assert.equal(g.players[0].bank[0].id,house.id);assert.equal(g.players[1].bank[0].id,hotel.id);assert.equal(group.buildings.length,0)});
test('wild moves are free, valid-colour-only, and cannot occur on another player turn',()=>{const g=fixture(),wild=card(g,0,c=>c.wild&&c.colors.length===2&&c.colors.includes('brown'));act(g,0,{type:'play',card:wild,color:'brown'});act(g,0,{type:'move',card:wild,color:'sky'});assert.equal(g.plays,1);assert.equal(g.players[0].groups[0].color,'sky');assert.throws(()=>act(g,0,{type:'move',card:wild,color:'blue'}));assert.throws(()=>act(g,1,{type:'move',card:wild,color:'brown'}))});
test('winner needs three different colours and can claim only on own turn',()=>{const g=fixture();gr(g,1,'brown',2);gr(g,1,'blue',2);gr(g,1,'utility',2);assert.equal(sets(g.players[1]),3);assert.equal(g.winner,null);act(g,0,{type:'end'},rng);assert.equal(g.winner,1);assert.equal(g.phase,'finished')});
test('rejected commands are atomic and stale revisions cannot replay a move',()=>{const room=createRoom('ABCDEF','Host');join(room,'Guest');command(room,0,{type:'start',revision:room.revision});const saved=JSON.stringify(room);assert.throws(()=>command(room,0,{type:'play',revision:room.revision,card:'fake'}));assert.equal(JSON.stringify(room),saved);const rev=room.revision;command(room,0,{type:'end',revision:rev});assert.throws(()=>command(room,0,{type:'end',revision:rev}),/changed/);assert.ok(!JSON.stringify(snapshot(room,0)).includes(room.players[1].secret))});
test('seeded bot games complete and conserve all 106 cards',()=>{for(let seed=1;seed<=8;seed++){let s=seed;const random=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296};const g=newGame([{name:'A',bot:true},{name:'B',bot:true},{name:'C',bot:true}],random);let moves=0;while(g.winner===null&&moves++<3000){const id=g.pending?.responder??g.turn;act(g,id,botMove(g,id),random);const ids=[...g.deck,...g.discard,...g.players.flatMap(p=>[...p.hand,...p.bank,...p.groups.flatMap(gr=>[...gr.cards,...gr.buildings])])].map(c=>c.id);assert.equal(ids.length,106);assert.equal(new Set(ids).size,106)}assert.notEqual(g.winner,null,'bots should finish seed '+seed)}});
